### ISSUE TITLE
little variable mistake

### ISSUE THREAD

**Issue by x2ss** [PacktPublishing/Computer-Vision-with-Python-3#2]
https://github.com/PacktPublishing/Computer-Vision-with-Python-3/blob/fe36550648ba3c312cefb26e652caed6a7c9104e/Chapter10/codes/face_detection.py#L15

Hi, I think the referred code should be img_gray instead of gray, which is not defined previously. 

Thank your share and best regards!

**Comment by shubham763** [comment]
@x2ss The changes have been made thanks!
